### ISSUE TITLE
Anvil.http doesn't work on windows?

### ISSUE THREAD

**Issue by szkrd** [anviljs/anvil.http#2]
After `anvil install anvil.http` I want to run the anvil host, but this is what I get:

```
Installation of 'anvil.http' completed successfully.

c:\szabi\dev\www\sandbox\anvil\browsertest>anvil --host --ci --browser
   info  - socket.io started
Starting HTTP host at port 3080
Error configuring extension 'anvil.http' : TypeError: Cannot read property 'anvil.transform' of undefined
TypeError: Cannot read property 'anvil.transform' of undefined
    at module.exports.anvil.plugin.configure (C:\Users\szabi\.anvilextensions\node_modules\anvil.http\lib\http.js:101:22)
    at ExtensionContainer.configureExtensions (C:\Users\szabi\AppData\Roaming\npm\node_modules\anvil.js\lib\extensionContainer.js:44:16)
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\szabi\AppData\Roaming\npm\node_modules\anvil.js\node_modules\underscore\underscore.js:78:11)
    at ExtensionContainer.configureExtensions (C:\Users\szabi\AppData\Roaming\npm\node_modules\anvil.js\lib\extensionContainer.js:38:5)
    at fireSub (C:\Users\szabi\AppData\Roaming\npm\node_modules\anvil.js\node_modules\monologue.js\lib\monologue.js:198:30)
    at Monologue.emit (C:\Users\szabi\AppData\Roaming\npm\node_modules\anvil.js\node_modules\monologue.js\lib\monologue.js:296:20)
    at Function._.each._.forEach (C:\Users\szabi\AppData\Roaming\npm\node_modules\anvil.js\node_modules\underscore\underscore.js:86:24)
    at Monologue.emit (C:\Users\szabi\AppData\Roaming\npm\node_modules\anvil.js\node_modules\monologue.js\lib\monologue.js:292:8)
    at Anvil.onConfig (C:\Users\szabi\AppData\Roaming\npm\node_modules\anvil.js\lib\anvil.js:113:8)
Extension 'anvil.http' cannot be configured and has been disabled
```

I have VS C++ Express, so socket.io _does_ build, though I have two v8 warnings (but I doubt that's the problem). Do I have to set up something in build.json?

**Comment by szkrd** [comment]
Sorry, I guess I shoule move this to the main anvil issue list.
